### ISSUE TITLE
go through the slappers in the BTB hub for some that are not working or irrevlant.

### ISSUE THREAD

**Issue by Jackgt720** [BreathTakinglyBinary/Bedrock-Servers#5]

**Comment by ToukaGontier** [comment]
Removed these Slappers from the Hub:
HG 
MiniGames 
Prison
SkyWars 
RolePlay 

The SkyBlock Slapper + Portal are currently inactive. 

Left the other Slappers/NPC's alone as they contribute to the Hub's design.

**Comment by ToukaGontier** [comment]
Added a plugin made by Realm going by the name of **SimpleTransfer_v1.0.0**
Which allows you to use the command "transfer {player} (IP) (Port)" in Slappers.

Added the command to the existing SkyBlock Slapper. Though some additional changes may occur from issue  #13 

Closing as the main issue is resolved ~
